[tools]
aws-cli = { version = "2.34.0", symlink_bins = "true" }
gh = "2.87.3"
jq = "1.8.1"
k9s = "0.50.18"
kubectl = "1.35.2"
node = "lts/krypton"
python = "3.14.3"
postgres = "15.16"
pulumi = "3.224.0"
uv = "0.10.7"
